name: archive/functionGraphDemo
on:
  push:
    paths:
      - 'archive/functionGraphDemo/**'
      - '.github/workflows/functionGraphDemo.yml'
  pull_request:
    paths:
      - 'archive/functionGraphDemo/**'
      - '.github/workflows/functionGraphDemo.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'functionGraphDemo'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'nodejs,R,ruby'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run 'functionGraphDemo'
        run: |
          cd archive/functionGraphDemo
          npm install
          $GRAALVM_HOME/bin/node --version
          $GRAALVM_HOME/bin/node --jvm --polyglot server.js &
          sleep 60
          curl http://localhost:8088/
