name: native-aws-lambda
on:
  push:
    paths:
      - 'native-aws-lambda/**'
      - '.github/workflows/native-aws-lambda.yml'
  pull_request:
    paths:
      - 'native-aws-lambda/**'
      - '.github/workflows/nativeaws-lambda.yml'
  schedule:
    - cron: "0 0 1 * *" # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'native-aws-lambda'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run 'native-aws-lambda java'
        run: |
          cd native-aws-lambda
          ./mvnw package
      - name: Run 'native-aws-lambda native image'
        run: |
          cd native-aws-lambda
          ./mvnw package -Dpackaging=docker-native