name: native-image/wasm-spring-shell
on:
  push:
    paths:
      - 'native-image/wasm-spring-shell/**'
      - '.github/workflows/native-image-wasm-spring-shell.yml'
  pull_request:
    paths:
      - 'native-image/wasm-spring-shell/**'
      - '.github/workflows/native-image-wasm-spring-shell.yml'
  schedule:
    - cron: "0 0 1 * *"  # run every month
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: Run 'native-image/wasm-spring-shell'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        java-version: ['25e1-ea']
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Set up Binaryen
        run: |
          curl -sLO https://github.com/WebAssembly/binaryen/releases/download/version_122/binaryen-version_122-x86_64-linux.tar.gz
          tar xzf binaryen-version_122-x86_64-linux.tar.gz
          echo "$(pwd)/binaryen-version_122/bin" >> "$GITHUB_PATH"
      - name: Run 'native-image/wasm-spring-shell'
        run: |
          cd native-image/wasm-spring-shell
          ./mvnw --no-transfer-progress -Pnative native:compile
          node --experimental-wasm-exnref target/wasm-spring-shell help
          node --experimental-wasm-exnref target/wasm-spring-shell hello Jane
